set(BFLIB_MAJOR_VERSION 0)
set(BFLIB_MINOR_VERSION 1)
set(BFLIB_PATCH_VERSION 0)

set(BFLIB_VERSION ${BFLIB_MAJOR_VERSION}.${BFLIB_MINOR_VERSION}.${BFLIB_PATCH_VERSION})

message(STATUS "Building bflib version ${BFLIB_VERSION}")
